[package]
name = "gguf"
version = "0.0.1"
description = "Parser and struct to handle GGUF files' header and metadata info"
edition = "2021"
license = "MIT"

[dependencies]
nom = { version = "7", features = ["alloc"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = { version = "0.9", optional = true }

[features]
bin = ["serde_yaml"]

[[bin]]
name = "gguf-info"
required-features = ['bin']
