[package]
name = "gguf"
version = "0.0.1"
description = "Parser and struct to handle GGUF files' header and metadata info"
edition = "2021"
license = "MIT"

[dependencies]
nom = { version = "7", features = ["alloc"] }
log = { version = "0.4", optional = true }

[features]
bin = ["log"]

[[bin]]
name = "gguf-info"
required-features = ['bin']
