[package]
name = "gguf"
version = "0.0.1"
description = "Parser and struct to handle GGUF files' header and metadata info"
edition = "2021"
license = "MIT"

[dependencies]
nom = "7"

[[bin]]
name = "gguf-info"
